export global GruvboxPalette {
    out property <color> bg0-hard: #1d1f21;
    out property <color> bg0: #282828;
    out property <color> bg1: #3c3836;
    out property <color> bg2: #504945;
    out property <color> bg3: #665c54;
    out property <color> bg4: #7c6f64;
    out property <color> fg0: #ebdbb2;
    out property <color> fg1: #ebdbb2;
    out property <color> fg2: #d5c4a1;
    out property <color> fg3: #bdae93;
    out property <color> fg4: #a89984;
    out property <color> red: #ca5345;
    out property <color> green: #98971a;
    out property <color> yellow: #d79921;
    out property <color> blue: #458588;
    out property <color> purple: #cf7aa0;
    out property <color> aqua: #689d6a;
    out property <color> orange: #d65d0e;
    out property <color> red-dim: #ff6b5b;
    out property <color> green-dim: #b8bb26;
    out property <color> yellow-dim: #fabd2f;
    out property <color> blue-dim: #83a598;
    out property <color> purple-dim: #d3869b;
    out property <color> aqua-dim: #8ec07c;
    out property <color> orange-dim: #fe8019;
}
